####################
#
# Example Job for HTCondor
#
####################

#---------------------------------------------
# Name your batch so it's easy to distinguish in the q.
JobBatchName = "Test"

# Make certain project spaces available in container
#### environment = "mount=$ENV(PWD)"

# --------------------------------------------
# Executable and its arguments
executable    = /usr/bin/bash
arguments = /mnt/fast/nobackup/users/ta01123/eat_apr30/fairseq/EAT_CkptMixRegionExtraMixLCls1Layer2S2TDrpInpTBothNoMixCls/scripts/pretraining_AS2M4G24.sh

# ---------------------------------------------------
# Universe (vanilla, docker)
universe = docker
docker_image = container-registry.surrey.ac.uk/shared-containers/ubuntu22fairseq@sha256:aeba04488eb0ea580f2e0dd1c70c0d6664e3ed91c36a8be295930d5477e08d72

# -------------------------------------------------
# Event, out and error logs
log    = c$(cluster).p$(process).log
output = c$(cluster).p$(process).out
error  = c$(cluster).p$(process).error

# -----------------------------------
# File Transfer, Input, Output
should_transfer_files = YES

# -------------------------------------
# Requirements for the Job (Requirements are explained in further detail in example09.submit_file)
# NOTE: HasStornext is not valid on orca.
requirements = (CUDACapability > 2.0) && (TARGET.Machine != "aisurrey12.surrey.ac.uk")

### change config.py bs to 64 and +GPUMem 35000 (for A100)
# --------------------------------------
# Resources
request_GPUs     = 4
# this needs to be specified for the AI@Surrey cluster if requesting a GPU
+GPUMem          = 22000  
request_CPUs     = 8
request_memory   = 70G


#This job will complete in less than 1 hour
+JobRunTime = 72

#This job can checkpoint
+CanCheckpoint = true

# -----------------------------------
# Queue commands
queue

